# Generated by Django 4.1.13 on 2025-11-10 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('medicine_type', models.CharField(default='TABLET', max_length=20)),
                ('dosage_strength', models.CharField(blank=True, max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=20)),
                ('DATE_OF_BIRTH', models.DateField()),
                ('GENDER', models.CharField(max_length=100)),
                ('ADDRESS', models.TextField()),
                ('sleep_start_time', models.TimeField(default='22:00')),
                ('sleep_end_time', models.TimeField(default='06:00')),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_start_time', models.DateTimeField()),
                ('sleep_end_time', models.DateTimeField(blank=True, null=True)),
                ('sleep_duration', models.IntegerField(blank=True, null=True)),
                ('sleep_quality_score', models.IntegerField(blank=True, null=True)),
                ('wake_up_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('PATIENT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('scheduled_time', models.TimeField()),
                ('frequency', models.CharField(default='DAILY', max_length=20)),
                ('days_of_week', models.CharField(default='1,2,3,4,5,6,7', help_text='Comma separated days (1=Monday, 7=Sunday)', max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('MEDICINE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
                ('PATIENT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='PATIENT',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.CharField(max_length=100)),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('voice_transcription', models.TextField(blank=True)),
                ('voice_audio_file', models.FileField(blank=True, null=True, upload_to='voice_commands/')),
                ('notes', models.TextField(blank=True)),
                ('MEDICINEPLAN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicineplan')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(max_length=20)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PATIENT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_specialization', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('PATIENT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
    ]
